#!/usr/bin/env python3
from __future__ import annotations

import argparse
import getpass
import json
import os
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR / "src"))

from tokenmessung.fixture import create_fixture  # noqa: E402
from tokenmessung.analyzer import TOOL_SANITY, decision_summary, explain_warning, human_bytes  # noqa: E402
from tokenmessung.runner import GENERATED_MARKER, audit_subject_source, new_batch_id, run_benchmark  # noqa: E402
from tokenmessung.schemas import TASKS  # noqa: E402


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run a local Codex AGENTS token benchmark.")
    parser.add_argument("--model", required=True)
    parser.add_argument("--subject-dir", type=Path, default=Path("subject"))
    parser.add_argument("--run-dir", type=Path, default=Path("tokenmessung-run"))
    parser.add_argument("--repeats", type=int, default=1)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--task-id", action="append", dest="task_ids")
    parser.add_argument("--all-tasks", action="store_true")
    parser.add_argument("--heartbeat-seconds", type=float, default=10.0)
    parser.add_argument("--max-run-seconds", type=float, default=300.0)
    parser.add_argument("--subject-mode", choices=("package", "agents-md"), default="package")
    parser.add_argument("--history-dir", type=Path, default=Path("tokenmessung-history"))
    parser.add_argument("--no-archive-previous-result", action="store_true")
    return parser


def status(message: str) -> None:
    print(f"[tokenmessung] {message}", file=sys.stderr, flush=True)


def ensure_api_key() -> str:
    if os.environ.get("CODEX_API_KEY"):
        return "env"
    key = getpass.getpass("[tokenmessung] CODEX_API_KEY: ")
    if not key:
        raise SystemExit("CODEX_API_KEY is required.")
    os.environ["CODEX_API_KEY"] = key
    return "prompt"


def tool_sanity_text() -> str:
    return (
        "Tool sanity: "
        f"schema v{TOOL_SANITY['schema_version']}; "
        f"isolation reporting={'on' if TOOL_SANITY['run_isolation_reporting'] else 'off'}; "
        f"separated warnings={'on' if TOOL_SANITY['separated_warning_sections'] else 'off'}; "
        f"aggregated command output={'on' if TOOL_SANITY['aggregated_command_output_counted'] else 'off'}."
    )


def reset_run_dir(run_dir: Path, root: Path, subject_dir: Path) -> None:
    if run_dir == root:
        raise SystemExit("Refusing to use the current folder itself as --run-dir.")
    if run_dir == subject_dir or subject_dir.is_relative_to(run_dir):
        raise SystemExit("Refusing to place subject/ inside --run-dir because generated cleanup would remove it.")
    default_run_dir = (root / "tokenmessung-run").resolve()
    if run_dir.exists() and run_dir != default_run_dir and any(run_dir.iterdir()) and not (run_dir / GENERATED_MARKER).exists():
        raise SystemExit(f"Refusing to replace non-tokenmessung --run-dir without {GENERATED_MARKER}: {run_dir}")
    if run_dir.exists():
        shutil.rmtree(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / GENERATED_MARKER).write_text("generated by tokenmessung\n", encoding="utf-8")


def safe_slug(value: str) -> str:
    slug = "".join(char if char.isalnum() or char in ("-", "_") else "-" for char in value.strip())
    return slug.strip("-") or "run"


def archive_previous_result(run_dir: Path, history_dir: Path) -> Path | None:
    result_json = run_dir / "result.json"
    if not result_json.is_file() or not (run_dir / GENERATED_MARKER).exists():
        return None
    try:
        result = json.loads(result_json.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        result = {}
    context = result.get("context", {}) if isinstance(result, dict) else {}
    integrity = result.get("integrity", {}) if isinstance(result, dict) else {}
    task_ids = context.get("task_ids", []) if isinstance(context, dict) else []
    if isinstance(task_ids, list) and task_ids:
        task_slug = safe_slug("-".join(str(task_id) for task_id in task_ids))
    else:
        task_slug = "unknown-task"
    batch = str(integrity.get("batch_id", "")) if isinstance(integrity, dict) else ""
    batch_slug = safe_slug(batch[:8] or "no-batch")
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    archive_base = history_dir / f"{timestamp}-{task_slug}-{batch_slug}"
    archive_dir = archive_base
    suffix = 2
    while archive_dir.exists():
        archive_dir = history_dir / f"{archive_base.name}-{suffix}"
        suffix += 1
    archive_dir.mkdir(parents=True, exist_ok=False)
    copied: list[str] = []
    for name in ("RESULT.md", "CODEX_HANDOFF.md", "result.json", "summary.csv", "summary.json", "paired-deltas.csv"):
        source = run_dir / name
        if source.is_file():
            shutil.copy2(source, archive_dir / name)
            copied.append(name)
    (archive_dir / GENERATED_MARKER).write_text("archived by tokenmessung\n", encoding="utf-8")
    (archive_dir / "archive.json").write_text(
        json.dumps({"source_run_dir": str(run_dir), "copied_files": copied}, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return archive_dir


def render_progress(event: dict[str, object]) -> None:
    event_name = event.get("event")
    if event_name == "benchmark_start":
        status(f"Benchmark starting: {event.get('total_runs')} runs, {event.get('repeats')} repeat(s), {event.get('task_count')} task(s).")
    elif event_name == "run_start":
        status(
            "Run {run_order}/{total_runs} starting: {task_id} [{variant}] repeat {repeat}.".format(
                run_order=event.get("run_order"),
                total_runs=event.get("total_runs"),
                task_id=event.get("task_id"),
                variant=event.get("variant"),
                repeat=event.get("repeat"),
            )
        )
    elif event_name == "run_heartbeat":
        status(f"Run {event.get('run_id')} has been running for {event.get('elapsed_seconds')}s.")
    elif event_name == "run_timeout":
        status(f"Run {event.get('run_id')} stopped after {event.get('max_run_seconds')}s.")
    elif event_name == "run_done":
        status(
            "Run {run_order}/{total_runs} complete: {task_id} [{variant}], exit {exit_code}, {wall_seconds}s.".format(
                run_order=event.get("run_order"),
                total_runs=event.get("total_runs"),
                task_id=event.get("task_id"),
                variant=event.get("variant"),
                exit_code=event.get("exit_code"),
                wall_seconds=event.get("wall_seconds"),
            )
        )
    elif event_name == "analysis_start":
        status("Analysis starting.")
    elif event_name == "analysis_done":
        status("Analysis complete.")


def format_delta(value: object) -> str:
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return "n/a"
    if numeric.is_integer():
        return f"{int(numeric):,}"
    return f"{numeric:,.1f}"


def print_result(result: dict[str, object]) -> None:
    primary = result.get("primary_delta", {})
    quality = result.get("quality", {})
    benchmark_warnings = result.get("benchmark_warnings", result.get("warnings", []))
    artifacts = result.get("artifacts", {})
    subject = result.get("subject", {})
    final_relevant = result.get("final_relevant_files", {})
    reliability = result.get("reliability", {})
    tool_sanity = result.get("tool_sanity", {})
    integrity = result.get("integrity", {})
    decision = result.get("decision", {})
    if not isinstance(decision, dict) or not decision:
        decision = decision_summary(result)
    percent = primary.get("percent") if isinstance(primary, dict) else None
    percent_text = "n/a" if percent is None else f"{float(percent):+.1f}%"
    print("\n=== Tokenmessung Result ===")
    print(f"Verdict: {result.get('verdict', 'unknown')}")
    isolation = result.get("isolation", {})
    if isinstance(isolation, dict):
        print(f"Isolation: ~/.codex excluded = {isolation.get('home_codex_excluded', False)}")
    if isinstance(subject, dict):
        print(f"Subject: {subject.get('mode', 'n/a')} / {format_delta(subject.get('source_file_count'))} files / {human_bytes(subject.get('total_bytes'))} ({format_delta(subject.get('total_bytes'))} bytes)")
    if isinstance(integrity, dict):
        print(f"Batch: {integrity.get('batch_id', 'n/a')}")
        print(f"Subject fingerprint: {integrity.get('subject_fingerprint', 'n/a')}")
        print(f"Run config fingerprint: {integrity.get('run_config_fingerprint', 'n/a')}")
    if isinstance(primary, dict):
        print(f"Paired median non-cached input delta: {format_delta(primary.get('agents_minus_control'))} ({percent_text})")
        print(
            "Variant medians: agents {agents} / control {control}".format(
                agents=format_delta(primary.get("agents_median")),
                control=format_delta(primary.get("control_median")),
            )
        )
    if isinstance(quality, dict):
        print(f"Quality: agents {quality.get('agents_success_rate', 'n/a')} / control {quality.get('control_success_rate', 'n/a')}")
    if isinstance(final_relevant, dict):
        print(f"Repo-relative relevant_files only: {final_relevant.get('repo_relative_only', False)}")
        print(f"Normalized repo-relative relevant_files only: {final_relevant.get('normalized_repo_relative_only', False)}")
    if isinstance(reliability, dict):
        paired_runs = reliability.get("paired_runs", "n/a")
        level = reliability.get("level", "n/a")
        print(f"Reliability: {level} ({paired_runs} paired run(s))")
        for warning in reliability.get("warnings", []):
            print(f"- {warning}: {explain_warning(str(warning))}")
    print(f"Next action: {decision.get('next_action', 'unknown')}")
    print(f"Decision reason: {decision.get('reason', 'unknown')}")
    if isinstance(tool_sanity, dict):
        print(
            "Tool sanity: schema v{schema}; isolation reporting={isolation}; separated warnings={warnings}; aggregated output={output}".format(
                schema=tool_sanity.get("schema_version", "n/a"),
                isolation=tool_sanity.get("run_isolation_reporting", False),
                warnings=tool_sanity.get("separated_warning_sections", False),
                output=tool_sanity.get("aggregated_command_output_counted", False),
            )
        )
    if benchmark_warnings:
        print("Benchmark warnings:")
        for warning in benchmark_warnings:
            print(f"- {warning}: {explain_warning(str(warning))}")
    else:
        print("Benchmark warnings: none")
    if isinstance(subject, dict):
        subject_warnings = subject.get("warnings", [])
        if subject_warnings:
            print(f"Subject notes: {len(subject_warnings)} note(s); see RESULT.md for details.")
    if isinstance(artifacts, dict):
        print(f"Human report: {artifacts.get('result_md')}")
        print(f"Machine report: {artifacts.get('result_json')}")
        if artifacts.get("codex_handoff_md"):
            print(f"Codex handoff: {artifacts.get('codex_handoff_md')}")
    print()


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.all_tasks and args.task_ids:
        raise SystemExit("Use either --all-tasks or --task-id, not both.")
    root = Path.cwd().resolve()
    subject_arg = args.subject_dir.expanduser()
    subject_dir = (subject_arg if subject_arg.is_absolute() else root / subject_arg).resolve()
    if not (subject_dir / "AGENTS.md").is_file():
        raise SystemExit(f"Missing required file: {subject_dir / 'AGENTS.md'}")
    status(f"Subject checked: {subject_dir}")
    agents_file = None
    agents_dir = None
    if args.subject_mode == "package":
        agents_dir = subject_dir
    else:
        agents_file = subject_dir / "AGENTS.md"
    subject_audit = audit_subject_source(agents_file, agents_dir, subject_mode=args.subject_mode)
    batch_id = new_batch_id()
    status(
        "Subject audit: {mode}, {files} file(s), size {size}.".format(
            mode=subject_audit["mode"],
            files=subject_audit["file_count"],
            size=f"{human_bytes(subject_audit['total_bytes'])} ({subject_audit['total_bytes']} bytes)",
        )
    )
    largest_files = subject_audit.get("largest_files", [])
    if largest_files:
        top = ", ".join(f"{item['path']} ({human_bytes(item['bytes'])}, {item['bytes']} bytes)" for item in largest_files[:3])
        status(f"Largest subject files: {top}.")
    warnings = subject_audit.get("warnings", [])
    if warnings:
        status("Subject warnings:")
        for warning in warnings:
            status(f"- {warning}: {explain_warning(str(warning))}")

    run_dir = (root / args.run_dir).resolve()
    history_dir = (root / args.history_dir).resolve()
    raw_dir = run_dir / "raw"
    fixture_dir = raw_dir / "fixture"
    results_dir = raw_dir / "results"
    workspaces_dir = raw_dir / "workspaces"
    task_ids = None if args.all_tasks else (args.task_ids or [TASKS[0]["id"]])
    planned_task_count = len(TASKS) if task_ids is None else len(task_ids)
    planned_runs = args.repeats * planned_task_count * 2
    status(tool_sanity_text())
    status(f"Batch ID: {batch_id}")
    status(f"Subject fingerprint: {subject_audit.get('fingerprint', 'n/a')}")
    status(f"Planned paid Codex runs: {planned_runs} ({planned_task_count} task(s) x {args.repeats} repeat(s) x 2 variants).")

    key_source = ensure_api_key()
    status("API key detected in environment." if key_source == "env" else "API key entered locally.")
    status("Run isolation: dedicated CODEX_HOME per run; ~/.codex is not measured as an instruction source.")
    if run_dir.exists():
        if not args.no_archive_previous_result:
            archived = archive_previous_result(run_dir, history_dir)
            if archived is not None:
                status(f"Archived previous compact report: {archived}")
        status(f"Replacing previous run folder: {run_dir}")
    reset_run_dir(run_dir, root, subject_dir)
    if task_ids is None:
        status("Task selection: all tasks.")
    else:
        status(f"Task selection: {', '.join(task_ids)}.")
    status(f"Creating fixture: {fixture_dir}")
    create_fixture(fixture_dir, force=True)
    status(f"Fixture ready. Planned runs: {planned_runs}")
    started = time.monotonic()
    outputs = run_benchmark(
        fixture_dir,
        agents_file,
        args.model,
        args.repeats,
        results_dir,
        seed=args.seed,
        agents_dir=agents_dir,
        workspace_root=workspaces_dir,
        progress=render_progress,
        heartbeat_interval=args.heartbeat_seconds,
        max_run_seconds=args.max_run_seconds,
        task_ids=task_ids,
        analysis_dir=run_dir,
        subject_mode=args.subject_mode,
        batch_id=batch_id,
    )
    result = json.loads(outputs["result_json"].read_text(encoding="utf-8"))
    result["run_config"] = {
        "all_tasks": args.all_tasks,
        "heartbeat_seconds": args.heartbeat_seconds,
        "max_run_seconds": args.max_run_seconds,
        "model": args.model,
        "repeats": args.repeats,
        "seed": args.seed,
        "subject_mode": args.subject_mode,
        "subject_dir": str(subject_dir),
        "task_ids": task_ids,
    }
    result["artifacts"]["raw_dir"] = str(raw_dir)
    outputs["result_json"].write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    status(f"Report ready after {round(time.monotonic() - started, 1)}s: {outputs['result_md']}")
    print_result(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
